#Sarah Knipp
#Week 4 - Question 4
#Draw this pretty pattern

import turtle

wn = turtle.Screen()
wn.bgcolor("black")
wn.title("Sarah Knipp Week 4 Question 1")

kevin = turtle.Turtle()
kevin.pensize(8)
kevin.shape("turtle")
kevin.fillcolor("fuchsia")
kevin.speed(8)
kevin.color("blueviolet")



 
def DrawSquare ():
    """Draw one square"""
    for i in range(4):
        kevin.forward (250) #length of line
        kevin.left(90)     #angle
        
        


DrawSquare()
kevin.left(20)
DrawSquare()
kevin.left(20)
DrawSquare()
kevin.left(20)
DrawSquare()
kevin.left(20)
DrawSquare()
kevin.left(20)
DrawSquare()
kevin.left(20)
DrawSquare()
kevin.left(20)
DrawSquare()
kevin.left(20)
DrawSquare()
kevin.left(20)
DrawSquare()
kevin.left(20)
DrawSquare()
kevin.left(20)
DrawSquare()
kevin.left(20)
DrawSquare()
kevin.left(20)
DrawSquare()
kevin.left(20)
DrawSquare()
kevin.left(20)
DrawSquare()
kevin.left(20)
DrawSquare()
kevin.left(20)

#Next Set
DrawSquare()
kevin.pensize(2)
kevin.color("DeepPink")
kevin.left(20)
DrawSquare()
kevin.pensize(2)
kevin.color("DeepPink")
kevin.left(20)
DrawSquare()
kevin.pensize(2)
kevin.color("DeepPink")
kevin.left(20)
DrawSquare()
kevin.pensize(2)
kevin.color("DeepPink")
kevin.left(20)
DrawSquare()
kevin.pensize(2)
kevin.color("DeepPink")
kevin.left(20)
DrawSquare()
kevin.pensize(2)
kevin.color("deeppink")
kevin.left(20)
DrawSquare()
kevin.pensize(2)
kevin.color("deeppink")
kevin.left(20)
DrawSquare()
kevin.pensize(2)
kevin.color("deeppink")
kevin.left(20)
DrawSquare()
kevin.pensize(2)
kevin.color("DeepPink")
kevin.left(20)
DrawSquare()
kevin.pensize(2)
kevin.color("DeepPink")
kevin.left(20)
DrawSquare()
kevin.pensize(2)
kevin.color("DeepPink")
kevin.left(20)
DrawSquare()
kevin.pensize(2)
kevin.color("DeepPink")
kevin.left(20)
DrawSquare()
kevin.pensize(2)
kevin.color("DeepPink")
kevin.left(20)
DrawSquare()
kevin.pensize(2)
kevin.color("DeepPink")
kevin.left(20)
DrawSquare()
kevin.pensize(2)
kevin.color("DeepPink")
kevin.left(20)
DrawSquare()
kevin.pensize(2)
kevin.color("DeepPink")
kevin.left(20)
DrawSquare()
kevin.pensize(2)
kevin.color("DeepPink")
kevin.left(20)
DrawSquare()
kevin.pensize(2)
kevin.color("DeepPink")
kevin.left(20)
DrawSquare()
kevin.pensize(2)
kevin.color("DeepPink")
kevin.left(20)

#Next set
DrawSquare()
kevin.pensize(.5)
kevin.color("white")
kevin.left(20)
DrawSquare()
kevin.pensize(.5)
kevin.color("deeppink")
kevin.left(20)
DrawSquare()
kevin.pensize(.5)
kevin.color("white")
kevin.left(20)
DrawSquare()
kevin.pensize(.5)
kevin.color("deeppink")
kevin.left(20)
DrawSquare()
kevin.pensize(.5)
kevin.color("white")
kevin.left(20)
DrawSquare()
kevin.pensize(.5)
kevin.color("deeppink")
kevin.left(20)
DrawSquare()
kevin.pensize(.5)
kevin.color("white")
kevin.left(20)
DrawSquare()
kevin.pensize(.5)
kevin.color("deeppink")
kevin.left(20)
DrawSquare()
kevin.pensize(.5)
kevin.color("white")
kevin.left(20)
DrawSquare()
kevin.pensize(.5)
kevin.color("deeppink")
kevin.left(20)
DrawSquare()
kevin.pensize(.5)
kevin.color("white")
kevin.left(20)
DrawSquare()
kevin.pensize(.5)
kevin.color("deeppink")
kevin.left(20)
DrawSquare()
kevin.pensize(.5)
kevin.color("white")
kevin.left(20)
DrawSquare()
kevin.pensize(.5)
kevin.color("deeppink")
kevin.left(20)
DrawSquare()
kevin.pensize(.5)
kevin.color("white")
kevin.left(20)
DrawSquare()
kevin.pensize(.5)
kevin.color("deeppink")
kevin.left(20)
DrawSquare()
kevin.pensize(.5)
kevin.color("white")
kevin.left(20)
DrawSquare()
kevin.pensize(.5)
kevin.color("deeppink")
kevin.left(20)
DrawSquare()
kevin.pensize(.5)
kevin.color("white")
kevin.left(20)